<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/5
 * Time: 23:50
 */

namespace common\models;


use cza\base\models\ModelTrait;
use yii\base\Model;

class BusinessConfigForm extends Model
{

    public $expired_time = '';
    public $notice = '';

    use ModelTrait;

    public function rules()
    {
        return [
            ['expired_time', 'default', 'value' => 6],
        ];
    }

    public function attributeLabels()
    {
        return [
            'expired_time' => '提前时间',
            'notice' => '提示语'
        ];
    }

    public function init()
    {
        $cache = \Yii::$app->cache;
        $this->expired_time = $cache->get('expired_time');
        $this->notice = $cache->get('notice');
        parent::init(); // TODO: Change the autogenerated stub
    }


}